spring.application.name=project
spring.datasource.url=jdbc:mysql://localhost:3307/magasin_temp?useSSL=true&allowPublicKeyRetrieval=true&requireSSL=true&serverTimezone=Africa/Casablanca
spring.datasource.username=root
spring.datasource.password=Lance
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

